version: '3.8'

services:
  app:
    build:
     context: ./app
     dockerfile: Dockerfile
    ports:
      - "7777:7777"
    volumes:
      - sqlite_data:/app/locations_data
    environment:
      - FLASK_ENV=development
#    command: python app.py

volumes:
  sqlite_data: